######################################################################
# Automatically generated by qmake (3.0) Mon Aug 22 11:34:37 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = dialer
INCLUDEPATH += .

# Input
HEADERS += Dialer.h
SOURCES += Dialer.cpp main.cpp
