######################################################################
# Automatically generated by qmake (3.0) Mon Aug 22 15:24:56 2016
######################################################################

QT += widgets
CONFIG += c++11
TEMPLATE = app
TARGET = dialer
INCLUDEPATH += .

# Input
HEADERS += Dialer.h
SOURCES += Dialer.cpp main.cpp
